CREATE TABLE orders1 (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
g_number VARCHAR(255) NOT NULL,
date DATETIME NOT NULL,
last_change_date DATE NOT NULL,
supplier_article VARCHAR(255) NOT NULL,
tech_size VARCHAR(255) NOT NULL,
barcode BIGINT NOT NULL,
total_price DECIMAL(10,2) NOT NULL,
discount_percent INT NOT NULL,
warehouse_name VARCHAR(255) NOT NULL,
oblast VARCHAR(255) NOT NULL,
income_id BIGINT NOT NULL,
odid VARCHAR(255) NOT NULL,
nm_id BIGINT NOT NULL,
subject VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL,
brand VARCHAR(255) NOT NULL,
is_cancel BOOLEAN NOT NULL DEFAULT FALSE,
cancel_dt DATETIME NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP


);
